"""Add sizes, material, and care_instructions to products

Revision ID: fcc58c3b7aa9
Revises: 31967832db9e
Create Date: 2026-03-07 14:18:18.830905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc58c3b7aa9'
down_revision = '31967832db9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('care_instructions', sa.Text(), nullable=True))
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('care_instructions')
        batch_op.drop_column('material')
        batch_op.drop_column('sizes')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
